### ISSUE TITLE
Colored output?

### ISSUE THREAD

**Issue by The-Compiler** [Gottox/irc-message-action#1]
Hey! :wave: 

Do you know if it's possible to get colored IRC messages? Based on the [mIRC color escapes](https://www.mirc.com/colors.html) I tried:

```yaml
        message: |-
          \0033[${{ github.workflow }}] Success: ${{ github.ref }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} triggered by ${{ github.actor }}\003
```

But that only lead to a literal `\003` in the message:

```
13:51 <qutebrowser-bot> \0033[CI] Success: refs/heads/master https://github.com/qutebrowser/qutebrowser/actions/runs/159237141 triggered by The-Compiler\003
```

**Comment by Gottox** [comment]
See this doc on how colors are encoded in irc: https://modern.ircdocs.horse/formatting.html

**Comment by The-Compiler** [comment]
That explains the same thing the mIRC page I linked above does (though, arguably, with a much nicer domain name :laughing:). However, I don't seem to be able to add an ASCII ETX into the text. No matter what I try (`\003`, `\u0003`, `&#x03;`, both with `|-` and `>-` introducing the YAML multiline string), I can't get the action (or GitHub's YAML parsing?) to interpret that as ASCII 0x03 rather than literal text.

**Comment by Gottox** [comment]
I see the issue:
```yaml
field: "\u000a"
field2: |-
  \u000a
```
results in:
```json
{
   "field": "\n",
   "field2": "\\u000a"
}
```

Basicly you must use quotes for your string, escaping in multiline strings isn't supported.

ref: https://stackoverflow.com/questions/35746109/how-to-do-unicode-escaping-in-yaml-multiline-string

**Comment by The-Compiler** [comment]
Ah, indeed, that worked! For some reason I get an initial space for the second line of the message (even if there are no spaces at all in the YAML file), but I don't care enough to investigate further.

For reference, here's the YAML abomination I ended up with:

```yaml
  irc:
    runs-on: ubuntu-latest
    needs: [linters, tests, tests-docker, codeql]
    if: always()
    steps:
    - name: Send success IRC notification
      uses: Gottox/irc-message-action@v1
      if: "needs.linters.result == 'success' && needs.tests.result == 'success' && needs.tests-docker.result == 'success' && needs.codeql.result == 'success'"
      with:
        server: chat.freenode.net
        channel: '#qutebrowser-dev'
        nickname: qutebrowser-bot
        message: "[${{ github.workflow }}] \u00033Success:\u0003 ${{ github.ref }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} triggered by ${{ github.actor }}"
    - name: Send non-success IRC notification
      uses: Gottox/irc-message-action@v1
      if: "needs.linters.result != 'success' || needs.tests.result != 'success' || needs.tests-docker.result != 'success' || needs.codeql.result != 'success'"
      with:
        server: chat.freenode.net
        channel: '#qutebrowser-dev'
        nickname: qutebrowser-bot
        message: "[${{ github.workflow }}] \u00034FAIL:\u0003 ${{ github.ref }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} triggered by ${{ github.actor }}\n
          linters: ${{ needs.linters.result }}, tests: ${{ needs.tests.result }}, tests-docker: ${{ needs.tests-docker.result }}, codeql: ${{ needs.codeql.result }}"
```

Thanks for the help!
